#!/bin/bash
#read from file and print average words per line
file=myfile.txt
words=`cat myfile.txt | wc -w`
lines=`cat myfile.txt | wc -l`
ans=$(echo "scale=2; $words / $lines" | bc)
echo "The average words per line of myfile.txt is $ans"
