#!/bin/bash
#read from text file. add values and computer average per line.
if [ -e $1 ]
then
	if [ -e $2 ]
	then
		if [ -e $3 ]
		then
			echo "$3 already exists... Overwriting."
			rm $3
		fi
		sort -u $1 > $3
		sort -u $2 > $3
	else
		echo "$2 doesnt exist."
	fi
else
	echo "$1 doesnt exist."
fi
