#!/bin/bash
#read from text file. add values and computer average per line.

file=$1
IFS=,
total=0
acc=0
if [ -e $file ]
then

	while read -r line
	do

		for x in $line
		do
			(( acc += 1 ))
			total=$(echo "scale=3; ($total+$x)" | bc)
		done

	done < $file
else
	echo "File does not exist"
fi
echo  "Total is $total"
avg=$(echo "scale=3; ($total/$acc)" | bc)
echo "Average is $total/$acc = $avg"
